# Generated by Django 2.2.6 on 2020-01-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yatranepal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packageName', models.CharField(max_length=200)),
                ('packageDesc', models.TextField()),
                ('packageImage', models.ImageField(upload_to='packages/')),
                ('packageSlug', models.CharField(max_length=50)),
                ('packagePrice', models.IntegerField()),
                ('packageFeatures', models.TextField()),
                ('placeName', models.ManyToManyField(to='yatranepal.Places')),
            ],
        ),
    ]
