# Generated by Django 2.2.6 on 2020-01-05 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yatranepal', '0002_packages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adventures',
            new_name='Adventure',
        ),
        migrations.RenameModel(
            old_name='Hotels',
            new_name='Hotel',
        ),
        migrations.RenameModel(
            old_name='Packages',
            new_name='Package',
        ),
        migrations.RenameModel(
            old_name='Places',
            new_name='Place',
        ),
    ]
