# Generated by Django 2.2.6 on 2020-01-06 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('yatranepal', '0003_auto_20200105_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adventure',
            name='adventureDesc',
            field=models.TextField(verbose_name='Adventure Description'),
        ),
        migrations.AlterField(
            model_name='adventure',
            name='adventureImage',
            field=models.ImageField(upload_to='adventures/', verbose_name='Adventure Image'),
        ),
        migrations.AlterField(
            model_name='adventure',
            name='adventureName',
            field=models.CharField(max_length=200, verbose_name='Name of Adventure'),
        ),
        migrations.AlterField(
            model_name='adventure',
            name='adventureSlug',
            field=models.CharField(max_length=50, verbose_name='Adventure URL'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotelAddress',
            field=models.CharField(max_length=255, verbose_name='Location of Hotel'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotelDesc',
            field=models.TextField(verbose_name='Hotel Description'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotelFeatures',
            field=models.TextField(verbose_name='Features of Hotel(in Points)'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotelImage',
            field=models.ImageField(upload_to='hotels/', verbose_name='Image of Hotel'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotelName',
            field=models.CharField(max_length=255, verbose_name='Name of the Hotel'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotelPrice',
            field=models.IntegerField(verbose_name='Price of Hotel per Room per day'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotelSlug',
            field=models.CharField(max_length=50, verbose_name='Hotel URL'),
        ),
        migrations.AlterField(
            model_name='package',
            name='packageDesc',
            field=models.TextField(verbose_name='Package Description'),
        ),
        migrations.AlterField(
            model_name='package',
            name='packageFeatures',
            field=models.TextField(verbose_name='Package Features'),
        ),
        migrations.AlterField(
            model_name='package',
            name='packageImage',
            field=models.ImageField(upload_to='packages/', verbose_name='Package Image'),
        ),
        migrations.AlterField(
            model_name='package',
            name='packageName',
            field=models.CharField(max_length=200, verbose_name='Package Name'),
        ),
        migrations.AlterField(
            model_name='package',
            name='packagePrice',
            field=models.IntegerField(verbose_name='Package Tentative Price(NRs)'),
        ),
        migrations.AlterField(
            model_name='package',
            name='packageSlug',
            field=models.CharField(max_length=50, verbose_name='Package URL'),
        ),
        migrations.AlterField(
            model_name='package',
            name='placeName',
            field=models.ManyToManyField(to='yatranepal.Place', verbose_name='Places that Lies in This Package'),
        ),
        migrations.AlterField(
            model_name='place',
            name='placeDesc',
            field=models.TextField(verbose_name='Place Description'),
        ),
        migrations.AlterField(
            model_name='place',
            name='placeImage',
            field=models.ImageField(upload_to='places/', verbose_name='Image of Place'),
        ),
        migrations.AlterField(
            model_name='place',
            name='placeName',
            field=models.CharField(max_length=255, verbose_name='Name of the Place'),
        ),
        migrations.AlterField(
            model_name='place',
            name='placeSlug',
            field=models.CharField(max_length=50, verbose_name='Place URL'),
        ),
        migrations.AlterField(
            model_name='transportation',
            name='fare',
            field=models.IntegerField(verbose_name='Price(NRs.)'),
        ),
        migrations.AlterField(
            model_name='transportation',
            name='placeFrom',
            field=models.CharField(max_length=200, verbose_name='Source Place'),
        ),
        migrations.AlterField(
            model_name='transportation',
            name='placeTo',
            field=models.CharField(max_length=200, verbose_name='Destination Place'),
        ),
        migrations.AlterField(
            model_name='transportation',
            name='transportationType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yatranepal.TransportationType', verbose_name='TransportationType'),
        ),
        migrations.AlterField(
            model_name='transportationtype',
            name='transportationType',
            field=models.CharField(max_length=255, verbose_name='Transportation Type'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(max_length=150)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('dob', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
