# Generated by Django 2.2.6 on 2020-01-06 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yatranepal', '0004_auto_20200106_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profileImage',
            field=models.ImageField(default='', upload_to='users/', verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(max_length=100, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(max_length=150, verbose_name='Bio'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateField(verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Username'),
        ),
    ]
