# Generated by Django 2.2.6 on 2020-01-09 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yatranepal', '0006_remove_package_placename'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='placetheme',
            field=models.CharField(default='', max_length=500, verbose_name='Theme of the Place'),
        ),
    ]
