# Generated by Django 2.2.6 on 2020-01-09 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yatranepal', '0007_place_placetheme'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdventureToPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adventure', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='yatranepal.Place', verbose_name='Adventures in this Place')),
                ('place', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='yatranepal.Adventure', verbose_name='Places for this Adventure')),
            ],
        ),
    ]
