# Generated by Django 2.2.6 on 2020-01-10 09:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('yatranepal', '0011_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Your Rating on 5'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'reviewedFor')},
        ),
    ]
