# Generated by Django 2.2.6 on 2020-01-11 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yatranepal', '0014_auto_20200111_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdventuresInPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adventure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yatranepal.Adventure', verbose_name='Adventures in this Place')),
            ],
        ),
    ]
