# Generated by Django 2.2.6 on 2020-01-11 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yatranepal', '0015_adventuresinplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventuresinplace',
            name='place',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='yatranepal.Place', verbose_name='Name of the Place'),
        ),
    ]
