# Generated by Django 2.2.6 on 2020-01-11 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yatranepal', '0016_adventuresinplace_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adventuresinplace',
            name='adventure',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='yatranepal.Adventure', verbose_name='Adventures in this Place'),
        ),
        migrations.AlterField(
            model_name='adventuresinplace',
            name='place',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='yatranepal.Place', verbose_name='Places for this Adventure'),
        ),
    ]
