# Generated by Django 2.2.6 on 2020-01-18 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yatranepal', '0017_auto_20200111_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adventuresinplace',
            name='adventure',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='yatranepal.Adventure', verbose_name='Adventures in this Place'),
        ),
        migrations.AlterField(
            model_name='adventuresinplace',
            name='place',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='yatranepal.Place', verbose_name='Places for this Adventure'),
        ),
        migrations.AlterField(
            model_name='placeimage',
            name='place',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='yatranepal.Place', verbose_name='Name of the Place'),
        ),
        migrations.DeleteModel(
            name='AdventureToPlace',
        ),
    ]
