# Generated by Django 2.2.6 on 2020-02-16 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yatranepal', '0024_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.TextField(max_length=250, verbose_name='Your Status'),
        ),
    ]
