# Generated by Django 2.2.6 on 2020-02-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yatranepal', '0025_auto_20200216_2322'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'Statuses'},
        ),
        migrations.AlterField(
            model_name='package',
            name='packagePrice',
            field=models.IntegerField(verbose_name='Tentative Price of Package'),
        ),
    ]
