# Generated by Django 2.2.6 on 2020-02-23 18:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yatranepal', '0026_auto_20200223_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='current_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 24, 0, 41, 8, 534686), verbose_name='Current Date and Time'),
        ),
        migrations.AlterField(
            model_name='package',
            name='packagePrice',
            field=models.IntegerField(verbose_name='Package Tentative Price(NRs)'),
        ),
    ]
