# Generated by Django 2.2.6 on 2020-03-09 16:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yatranepal', '0027_auto_20200224_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='current_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 9, 22, 34, 40, 837198), verbose_name='Current Date and Time'),
        ),
        migrations.DeleteModel(
            name='Transportation',
        ),
        migrations.DeleteModel(
            name='TransportationType',
        ),
    ]
