# Generated by Django 2.2.6 on 2020-03-14 11:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yatranepal', '0028_auto_20200309_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileImage',
            field=models.ImageField(default='users/user_default.png', upload_to='users/', verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='status',
            name='current_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 14, 17, 9, 28, 294304), verbose_name='Current Date and Time'),
        ),
    ]
